export const Dummy = [
  {
    name: 'Name Of Golf Society',
    date: '02-05-20024',
    time: '11:25',
  },
  {
    name: 'Name Of Golf Society',
    date: '02-05-20024',
    time: '11:25',
  },
  {
    name: 'Name Of Golf Society',
    date: '02-05-20024',
    time: '11:25',
  },
  {
    name: 'Name Of Golf Society',
    date: '02-05-20024',
    time: '11:25',
  },
  {
    name: 'Name Of Golf Society',
    date: '02-05-20024',
    time: '11:25',
  },
  {
    name: 'Name Of Golf Society',
    date: '02-05-20024',
    time: '11:25',
  },
  {
    name: 'Name Of Golf Society',
    date: '02-05-20024',
    time: '11:25',
  },
  {
    name: 'Name Of Golf Society',
    date: '02-05-20024',
    time: '11:25',
  },
  {
    name: 'Name Of Golf Society',
    date: '02-05-20024',
    time: '11:25',
  },
  {
    name: 'Name Of Golf Society',
    date: '02-05-20024',
    time: '11:25',
  },
];

export const Previous = [
  {
    no: 'S.NO',
    name: 'Name of Golf Society',
    player: 'Name of Player',
    course: 'Name of Golf Course',
    slope: 'Slope Index',
    rating: 'Field Rating',
    deadline: 'Deadline',
    ags: 'AGS',
    ratio: 'Course Ratio',
    result: 'Result',
  },
  {
    no: '1',
    name: 'ABCD',
    player: 'Jhon Wick',
    course: 'Assassin',
    slope: '100',
    rating: '100',
    deadline: '0',
    ags: '100',
    ratio: '100',
    result: '100%',
  },
  {
    no: '2',
    name: 'ABCD',
    player: 'Jhon Wick',
    course: 'Assassin',
    slope: '100',
    rating: '100',
    deadline: '0',
    ags: '100',
    ratio: '100',
    result: '100%',
  },
  {
    no: '3',
    name: 'ABCD',
    player: 'Jhon Wick',
    course: 'Assassin',
    slope: '100',
    rating: '100',
    deadline: '0',
    ags: '100',
    ratio: '100',
    result: '100%',
  },
  {
    no: '4',
    name: 'ABCD',
    player: 'Jhon Wick',
    course: 'Assassin',
    slope: '100',
    rating: '100',
    deadline: '0',
    ags: '100',
    ratio: '100',
    result: '100%',
  },
  {
    no: '5',
    name: 'ABCD',
    player: 'Jhon Wick',
    course: 'Assassin',
    slope: '100',
    rating: '100',
    deadline: '0',
    ags: '100',
    ratio: '100',
    result: '100%',
  },
  {
    no: '6',
    name: 'ABCD',
    player: 'Jhon Wick',
    course: 'Assassin',
    slope: '100',
    rating: '100',
    deadline: '0',
    ags: '100',
    ratio: '100',
    result: '100%',
  },
  {
    no: '7',
    name: 'ABCD',
    player: 'Jhon Wick',
    course: 'Assassin',
    slope: '100',
    rating: '100',
    deadline: '0',
    ags: '100',
    ratio: '100',
    result: '100%',
  },
  {
    no: '8',
    name: 'ABCD',
    player: 'Jhon Wick',
    course: 'Assassin',
    slope: '100',
    rating: '100',
    deadline: '0',
    ags: '100',
    ratio: '100',
    result: '100%',
  },
  {
    no: '9',
    name: 'ABCD',
    player: 'Jhon Wick',
    course: 'Assassin',
    slope: '100',
    rating: '100',
    deadline: '0',
    ags: '100',
    ratio: '100',
    result: '100%',
  },
  {
    no: '10',
    name: 'ABCD',
    player: 'Jhon Wick',
    course: 'Assassin',
    slope: '100',
    rating: '100',
    deadline: '0',
    ags: '100',
    ratio: '100',
    result: '100%',
  },
  {
    no: '11',
    name: 'ABCD',
    player: 'Jhon Wick',
    course: 'Assassin',
    slope: '100',
    rating: '100',
    deadline: '0',
    ags: '100',
    ratio: '100',
    result: '100%',
  },
  {
    no: '12',
    name: 'ABCD',
    player: 'Jhon Wick',
    course: 'Assassin',
    slope: '100',
    rating: '100',
    deadline: '0',
    ags: '100',
    ratio: '100',
    result: '100%',
  },
  {
    no: '13',
    name: 'ABCD',
    player: 'Jhon Wick',
    course: 'Assassin',
    slope: '100',
    rating: '100',
    deadline: '0',
    ags: '100',
    ratio: '100',
    result: '100%',
  },
  {
    no: '14',
    name: 'ABCD',
    player: 'Jhon Wick',
    course: 'Assassin',
    slope: '100',
    rating: '100',
    deadline: '0',
    ags: '100',
    ratio: '100',
    result: '100%',
  },
  {
    no: '15',
    name: 'ABCD',
    player: 'Jhon Wick',
    course: 'Assassin',
    slope: '100',
    rating: '100',
    deadline: '0',
    ags: '100',
    ratio: '100',
    result: '100%',
  },
  {
    no: '16',
    name: 'ABCD',
    player: 'Jhon Wick',
    course: 'Assassin',
    slope: '100',
    rating: '100',
    deadline: '0',
    ags: '100',
    ratio: '100',
    result: '100%',
  },
  {
    no: '17',
    name: 'ABCD',
    player: 'Jhon Wick',
    course: 'Assassin',
    slope: '100',
    rating: '100',
    deadline: '0',
    ags: '100',
    ratio: '100',
    result: '100%',
  },
  {
    no: '18',
    name: 'ABCD',
    player: 'Jhon Wick',
    course: 'Assassin',
    slope: '100',
    rating: '100',
    deadline: '0',
    ags: '100',
    ratio: '100',
    result: '100%',
  },
  {
    no: '19',
    name: 'ABCD',
    player: 'Jhon Wick',
    course: 'Assassin',
    slope: '100',
    rating: '100',
    deadline: '0',
    ags: '100',
    ratio: '100',
    result: '100%',
  },
  {
    no: '20',
    name: 'ABCD',
    player: 'Jhon Wick',
    course: 'Assassin',
    slope: '100',
    rating: '100',
    deadline: '0',
    ags: '100',
    ratio: '100',
    result: '100%',
  },
];
export const Users = [
  {
    no: 'S.NO',
    name: 'User Name',
    mail: 'Email',
    result: 'Verified Email',
  },
  {
    no: '1',
    name: 'Jhon Wick',
    mail: 'jhonwick@gmail.com',
    result: "true",
  },
  {
    no: '2',
    name: 'Jhon Wick',
    mail: 'jhonwick@gmail.com',
    result: "false",
  },
  {
    no: '3',
    name: 'Jhon Wick',
    mail: 'jhonwick@gmail.com',
    result: "true",
  },
  {
    no: '4',
    name: 'Jhon Wick',
    mail: 'jhonwick@gmail.com',
    result: "false",
  },
  {
    no: '5',
    name: 'Jhon Wick',
    mail: 'jhonwick@gmail.com',
    result: "true",
  },
];
